### ISSUE TITLE
Spectrum is only showing one flat line

### ISSUE THREAD

**Issue by plin2** [dzach/nrfmon#9]
The Spectrum only shows an orange block of the same level of e.g. -67 dBm for alle frequencies. There is no difference in rssi from 860 to 880 MHz.

What could be the reason?

**Comment by dzach** [comment]
Can you post a screenshot showing what you describe?
What is your hardware?

**Comment by plin2** [comment]
My hardware is an Arduino nano ATmega328P with the RFM12B attached to it.
Before taking the screenshot I checked my wiring again and detected a mistake -  I mixed up IRQ and MISO (I followed the following wiring sketch since I didnt find any other)

![cookbook_rfm12b_connections](https://user-images.githubusercontent.com/3195189/37485899-16c103a8-288d-11e8-92b1-8ad672199fcd.png)

But even after that I get a sort of 'flatline' 

![nrfmon_screenshot](https://user-images.githubusercontent.com/3195189/37485925-2baf8bae-288d-11e8-9145-4cce2c6f8180.JPG)

My Arduino nano is connected to an x86 computer with openSUSE Leap 42.3 (64 bit).  You'll see the nrfmon software versions in the screenshot.

My Questions right now:
- Is the wiring correct?
- Does the Arduino pin layout from the sketch match the one in rf12mon.ino?
- How can I check if the communication between the Arduino nano and the RFM12B is working correctly?
- How do I started the scan process? Is clicking on the Scan button enough?
- Shoud the application (spectrum display) react immediately after sending something in the 868 MHz band oder do I need to send long enough for nrfmon to scan the whole band (I need to scann the range between 868.000 and 868.800 MHz to detect the frequencies of an FSK protocol)?

**Comment by dzach** [comment]
Your setup seems to be ok but the screenshot doesn't look right; it seems like you are either getting an overwhelmingly strong signal that's saturating the input, or possibly tha the rf stage of the RFM12B isn't working as it should? The best way to debug the radios without equipment (e.g. a logic analyzer and/or an oscilloscope) is to have two arduino-rfm12b systems communicate with each other. If they do communicate, then obviously you will know the radios are ok.

To answer your questions.

- Your wiring seems to be ok.
- To see if you are communicating with the radio, click 'Traffic' above the console at the right, and try changing some of the settings of the radio, e.g. the channel. You should see the command being sent to the radio, and then the response of the radio. If you only see the command sent by nrfmon to the radio, then there is a problem either with the communication, or with the _rf12mon.ino_ sketch you uploaded.
- Your screenshot shows you started the scan successfully. Yes, simply clicking 'Scan' starts the scan.
- If the setup works properly you will be able to see each scanline as it progresses in time. Of course the response cannot be 'instant'; after all, this is just a tiny radio that was not meant to be a spectrum analyzer, but we make it believe it is :-). So you have to either transmit long enough for your transmission to fall into the receive window, or to **scan a narrower band**. To do the latter, right click on the spectrum screen and try the options in the popup menu, e.g. click 'Limit scan width' and drag the mouse on the spectrum screen, around the frequency of interest. The narrower the band, the faster the scan will be. In your screeshot it seems you were scanning the entire 868 band; that takes about 1/2 to 1 second per scanline, if I recall correctly.

nrfmon can also receive packets sent by a similar transmitter, in 'Listen' mode. But to do so, you need to have set all relevant radio parameters correctly, on both transmitter and receiver (nrfmon) sides.

I don't have an active system running at this moment. If you want to see more details on how this monitor works, you may check [this long thread](https://jeelabs.net/boards/6/topics/715?page=1&r=1521) from the time nrfmon was developed. There are many images and explanations about its operation there.

Hopefully you will solve the problem soon.

**Comment by plin2** [comment]
Tnakks for the hints. In the meantime I started debugging de rf12mon.ino ksetch a little bit by putting some Serial.println(); behind the #if defined(RFMON_ARSSI) ... #endif. Seems as if one complete run takes about 1-2 seconds. So that will be my timeframe. From my understanding untill now I should get one 476 bytes line of rssi levels. I don't see that appearing in the Arduino IDE serial monitor. I tried to call rf12_lowbat() to check the communication wirth the RFM12B to receive either 0 or 1. No feedback.

I just tried your suggestion regarding 'Traffic'. The results looks like this

![nrfmon_screenshot_2](https://user-images.githubusercontent.com/3195189/37536281-6ca87f0e-294a-11e8-9d18-1cfa3f4b9ddd.JPG)

Some background information: I try to control my shutters via home automation. I got quite far with an device call SIGNALduino, but that d´can detect onla one frequency. Since the remote control for my shutters (more or less a no-name product) seems to by usinf FSK I#m looking for the second frequency. That might be at about 868.300 MHz, but my SIGNALduino transmitts at 868.00 MHz and the motors are reacting (but not always. So, my target right now is the band between 868.00 and 868.700 MHz. I'll press the remote button long enough.

What next?

**Comment by dzach** [comment]
From your last screenshot it seems like you are indeed communicating with theArduino Nano serialy, since you are reading _rf12mon.ino_'s signature in the reply ("xcvr rf12b ver 0.7.6 hw HeeNode..." etc).
If you know the band of interest, then using my suggestion above and narrowing the scan width will give you faster scanline times. You may need to check if the radio rf stage is still ok.

I'll mark this issue 'closed', as this doesn't seem to be a problem with nrfmon. Of cource you can still commend here, if you think there is more that can be done on the issue you are facing with the radio.

**Comment by plin2** [comment]
mmhh, even if I set Frequency to 868.3000 I don't see any spectrum.

When I have Traffic=on and Print packet data as raw, shouldn't I see some incoming rssi-message to produce a spectrum?

How can I tell that the Arduino is really communicating with the RFM12B? Would it show error messages if it couldn't?

What is #define RFMON_ARSSI 0 beeing used for?

**Comment by dzach** [comment]
- Please read my suggestions above, and the forum thread I linked to. You will find many answers there.
- Get a second arduino+rfm12b and try to make the two communicate with eachother, using these radios.
- Generally, if the radio cannot communicate with the arduino, the arduino hangs there waiting for an aswer and doesn't respond to serial communication with nrfmon. Your's does respond, therefore you should check for other problems.
